interface Resources {
  "generator": {
    "content.btn_random_match": "Match aleatório",
    "content.footer.heading": "Sem login, sem KYC, só match de ET",
    "content.footer.subheading": "Clique e reze pro algoritmo degen",
    "content.form.btn_submit": "Procurar match",
    "content.form.invalid_nft_id": "NFT ID inválido",
    "content.form.label": "ID do seu ET",
    "content.form.placeholder": "Digite o ID (0 a {{max}})",
    "content.heading.subtitle": "Escolha um modo e deixe o algoritmo degen trabalhar",
    "content.heading.title": "Encontre seu match",
    "content.mode.by_id": "Por ID",
    "content.mode.random": "Aleatório",
    "content.sticker.1": "NFA",
    "content.sticker.2": "DYOR",
    "content.sticker.3": "Aura++",
    "footer.anchor.github": "GitHub",
    "footer.anchor.opensea": "OpenSea",
    "footer.nft_count": "NF_ETs avistados na coleção",
    "header.sticker": "Degen",
    "header.subtitle": "Defizeros Edition",
    "header.title.1": "NF_ET",
    "header.title.2": "inder"
  },
  "match": {
    "content.action_btn.copy_link.label": "Copiar link",
    "content.action_btn.copy_link.success": "Copiado",
    "content.action_btn.download": "Baixar card",
    "content.action_btn.open_external_link": "Ver",
    "content.card.compatibility": "Compatibilidade",
    "content.card.sticker.1": "Et Approved",
    "content.card.sticker.2": "LFG",
    "content.card.versus": "vs",
    "content.footer.subtitle": "Se der ruim, gera outro e finge que era esse",
    "content.footer.title": "Manda no chat e marca o ET",
    "content.heading.subtitle": "O algoritmo degen encontrou um par cósmico",
    "content.heading.title": "Match Detectado!",
    "content.nft_card.img_alt": "Defizero",
    "content.nft_card.sticker": "Defizero",
    "header.btn_go_back": "Voltar",
    "header.btn_new_match": "Novo match",
    "header.title.1": "NF_ET",
    "header.title.2": "inder",
    "loading_state.message.1": "Procurando ET compatível",
    "loading_state.message.2": "Decidindo entre A, B ou C",
    "loading_state.message.3": "Calibrando algoritmo da nave",
    "loading_state.message.4": "Consultando oráculo alienígena",
    "loading_state.message.5": "Verificando com os caras lá",
    "share_card.content.img_alt": "Defizero",
    "share_card.content.match": "Match",
    "share_card.content.sticker.1": "Bullish",
    "share_card.content.sticker.2": "Alien mode",
    "share_card.footer.subtitle": "Defizeros Edition",
    "share_card.footer.title.1": "NF_ET",
    "share_card.footer.title.2": "inder",
    "share_card.header.sticker": "Defizeros",
    "share_card.header.title": "Match Detectado!"
  },
  "notFound": {
    "cta": "Voltar para o início",
    "description": "Oops! Página não encontrada",
    "title": "404"
  }
}

export default Resources;
